package com.kodesport.calculator.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CalculatorDesign extends CssLayout {
	protected Label _value;
	protected GridLayout _buttonGrid;
	protected Button _minus;
	protected Button _plus;
	protected Button _times;
	protected Button _divide;
	protected Button _7;
	protected Button _8;
	protected Button _9;
	protected Button _4;
	protected Button _5;
	protected Button _6;
	protected Button _1;
	protected Button _2;
	protected Button _3;
	protected Button _0;
	protected Button _72;
	protected Button _clear;
	protected Button _enter;

	public CalculatorDesign() {
		Design.read(this);
	}
}
